(part "CX3225FB24000C0FZZH1"
    (packageRef "CX3225FB24000C0FZZH1")
    (interface
        (port "1" (symbPinId 1) (portName "X'TAL_TERMINAL_(INPUT/OUTPUT)_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_TERMINAL_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "X'TAL_TERMINAL_(INPUT/OUTPUT)_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_TERMINAL_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "CX3225FB24000C0FZZH1")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Crystals 3.2x2.5mm 24MHz 7pF")
    (property "Datasheet_Link" "https://ele.kyocera.com/assets/products/crystal-device/specification/CX3225FB_7pF.pdf")
    (property "symbolName1" "CX3225FB24000C0FZZH1")
)
